insert into brands ( name, created_at, updated_at) values('3 EN 1',now(),now());
insert into brands ( name, created_at, updated_at) values('3M',now(),now());
insert into brands ( name, created_at, updated_at) values('ADEX',now(),now());
insert into brands ( name, created_at, updated_at) values('AEROJET',now(),now());
insert into brands ( name, created_at, updated_at) values('ALLEN',now(),now());
insert into brands ( name, created_at, updated_at) values('ALTURA SEGURA',now(),now());
insert into brands ( name, created_at, updated_at) values('ANCLO',now(),now());
insert into brands ( name, created_at, updated_at) values('APEX',now(),now());
insert into brands ( name, created_at, updated_at) values('AQUAMASTER',now(),now());
insert into brands ( name, created_at, updated_at) values('ARCE',now(),now());
insert into brands ( name, created_at, updated_at) values('ARDA',now(),now());
insert into brands ( name, created_at, updated_at) values('ARROW',now(),now());
insert into brands ( name, created_at, updated_at) values('AUSTROMEX',now(),now());
insert into brands ( name, created_at, updated_at) values('BARO',now(),now());
insert into brands ( name, created_at, updated_at) values('BARRILITO ',now(),now());
insert into brands ( name, created_at, updated_at) values('BELLOTA ',now(),now());
insert into brands ( name, created_at, updated_at) values('BERNA',now(),now());
insert into brands ( name, created_at, updated_at) values('BLACK LIGHT',now(),now());
insert into brands ( name, created_at, updated_at) values('BLACK&DECKER',now(),now());
insert into brands ( name, created_at, updated_at) values('BONDHUS',now(),now());
insert into brands ( name, created_at, updated_at) values('BOSCH',now(),now());
insert into brands ( name, created_at, updated_at) values('BOSTON',now(),now());
insert into brands ( name, created_at, updated_at) values('BRASSO',now(),now());
insert into brands ( name, created_at, updated_at) values('CABEL',now(),now());
insert into brands ( name, created_at, updated_at) values('CASTILLO',now(),now());
insert into brands ( name, created_at, updated_at) values('CELESTRON',now(),now());
insert into brands ( name, created_at, updated_at) values('CHAVEZ',now(),now());
insert into brands ( name, created_at, updated_at) values('CHM',now(),now());
insert into brands ( name, created_at, updated_at) values('CIFUNSA ',now(),now());
insert into brands ( name, created_at, updated_at) values('CIGUEÑA',now(),now());
insert into brands ( name, created_at, updated_at) values('CLEVELAND ',now(),now());
insert into brands ( name, created_at, updated_at) values('CN',now(),now());
insert into brands ( name, created_at, updated_at) values('COLLINS',now(),now());
insert into brands ( name, created_at, updated_at) values('COR-MEX',now(),now());
insert into brands ( name, created_at, updated_at) values('CORRADI',now(),now());
insert into brands ( name, created_at, updated_at) values('CRESCENT',now(),now());
insert into brands ( name, created_at, updated_at) values('CRESCO',now(),now());
insert into brands ( name, created_at, updated_at) values('CUERVO',now(),now());
insert into brands ( name, created_at, updated_at) values('DEACERO',now(),now());
insert into brands ( name, created_at, updated_at) values('DECA',now(),now());
insert into brands ( name, created_at, updated_at) values('DERMA',now(),now());
insert into brands ( name, created_at, updated_at) values('DEVCON',now(),now());
insert into brands ( name, created_at, updated_at) values('DEWALT',now(),now());
insert into brands ( name, created_at, updated_at) values('DIANA',now(),now());
insert into brands ( name, created_at, updated_at) values('DICA ',now(),now());
insert into brands ( name, created_at, updated_at) values('DISTON',now(),now());
insert into brands ( name, created_at, updated_at) values('DREMEL',now(),now());
insert into brands ( name, created_at, updated_at) values('DURACEL',now(),now());
insert into brands ( name, created_at, updated_at) values('DURAMIL',now(),now());
insert into brands ( name, created_at, updated_at) values('EGAMASTER',now(),now());
insert into brands ( name, created_at, updated_at) values('EL TIGRE',now(),now());
insert into brands ( name, created_at, updated_at) values('ELPRO',now(),now());
insert into brands ( name, created_at, updated_at) values('EMPIRE',now(),now());
insert into brands ( name, created_at, updated_at) values('ENERGY',now(),now());
insert into brands ( name, created_at, updated_at) values('ERCKO',now(),now());
insert into brands ( name, created_at, updated_at) values('ESCALUMEX',now(),now());
insert into brands ( name, created_at, updated_at) values('FANAL',now(),now());
insert into brands ( name, created_at, updated_at) values('FANDELI',now(),now());
insert into brands ( name, created_at, updated_at) values('FAVEL',now(),now());
insert into brands ( name, created_at, updated_at) values('FIERO',now(),now());
insert into brands ( name, created_at, updated_at) values('FIFA',now(),now());
insert into brands ( name, created_at, updated_at) values('FISCHER',now(),now());
insert into brands ( name, created_at, updated_at) values('FLOWGUARD',now(),now());
insert into brands ( name, created_at, updated_at) values('FOREST & GARDEN',now(),now());
insert into brands ( name, created_at, updated_at) values('FOSET',now(),now());
insert into brands ( name, created_at, updated_at) values('FOY',now(),now());
insert into brands ( name, created_at, updated_at) values('FRASA',now(),now());
insert into brands ( name, created_at, updated_at) values('FURIA',now(),now());
insert into brands ( name, created_at, updated_at) values('GARLOCK',now(),now());
insert into brands ( name, created_at, updated_at) values('GENFLUX',now(),now());
insert into brands ( name, created_at, updated_at) values('GIMSA',now(),now());
insert into brands ( name, created_at, updated_at) values('Gladiator',now(),now());
insert into brands ( name, created_at, updated_at) values('GOLFO',now(),now());
insert into brands ( name, created_at, updated_at) values('GONI',now(),now());
insert into brands ( name, created_at, updated_at) values('GREENFIELD',now(),now());
insert into brands ( name, created_at, updated_at) values('GRINDING',now(),now());
insert into brands ( name, created_at, updated_at) values('HAWK',now(),now());
insert into brands ( name, created_at, updated_at) values('HERHILD',now(),now());
insert into brands ( name, created_at, updated_at) values('HERMEX ',now(),now());
insert into brands ( name, created_at, updated_at) values('HPTR',now(),now());
insert into brands ( name, created_at, updated_at) values('IGOTO',now(),now());
insert into brands ( name, created_at, updated_at) values('INCOR ',now(),now());
insert into brands ( name, created_at, updated_at) values('INDE',now(),now());
insert into brands ( name, created_at, updated_at) values('INDUX',now(),now());
insert into brands ( name, created_at, updated_at) values('INFRA',now(),now());
insert into brands ( name, created_at, updated_at) values('INGERSOLL RAND',now(),now());
insert into brands ( name, created_at, updated_at) values('INSSU',now(),now());
insert into brands ( name, created_at, updated_at) values('IRVING',now(),now());
insert into brands ( name, created_at, updated_at) values('IRWIN',now(),now());
insert into brands ( name, created_at, updated_at) values('ITA',now(),now());
insert into brands ( name, created_at, updated_at) values('IUSA ',now(),now());
insert into brands ( name, created_at, updated_at) values('JACOBS',now(),now());
insert into brands ( name, created_at, updated_at) values('JYRSA',now(),now());
insert into brands ( name, created_at, updated_at) values('KELLER',now(),now());
insert into brands ( name, created_at, updated_at) values('KLEIN ',now(),now());
insert into brands ( name, created_at, updated_at) values('KLINTEK',now(),now());
insert into brands ( name, created_at, updated_at) values('KOLA LOKA',now(),now());
insert into brands ( name, created_at, updated_at) values('KPS',now(),now());
insert into brands ( name, created_at, updated_at) values('KUANI',now(),now());
insert into brands ( name, created_at, updated_at) values('KYO',now(),now());
insert into brands ( name, created_at, updated_at) values('LASCO',now(),now());
insert into brands ( name, created_at, updated_at) values('LD',now(),now());
insert into brands ( name, created_at, updated_at) values('LENOX ',now(),now());
insert into brands ( name, created_at, updated_at) values('LINMEX',now(),now());
insert into brands ( name, created_at, updated_at) values('LOCTITE',now(),now());
insert into brands ( name, created_at, updated_at) values('LORI',now(),now());
insert into brands ( name, created_at, updated_at) values('LUFKIN',now(),now());
insert into brands ( name, created_at, updated_at) values('MAGLITE',now(),now());
insert into brands ( name, created_at, updated_at) values('MAKITA',now(),now());
insert into brands ( name, created_at, updated_at) values('MARTINEZ',now(),now());
insert into brands ( name, created_at, updated_at) values('METROMEX',now(),now());
insert into brands ( name, created_at, updated_at) values('MIBER',now(),now());
insert into brands ( name, created_at, updated_at) values('MIKELS',now(),now());
insert into brands ( name, created_at, updated_at) values('MILLER',now(),now());
insert into brands ( name, created_at, updated_at) values('MILWAUKEE',now(),now());
insert into brands ( name, created_at, updated_at) values('MINESOTA',now(),now());
insert into brands ( name, created_at, updated_at) values('MONT HARD',now(),now());
insert into brands ( name, created_at, updated_at) values('MORSE',now(),now());
insert into brands ( name, created_at, updated_at) values('MUELA',now(),now());
insert into brands ( name, created_at, updated_at) values('MUELLER',now(),now());
insert into brands ( name, created_at, updated_at) values('MUNDIAL',now(),now());
insert into brands ( name, created_at, updated_at) values('NEO',now(),now());
insert into brands ( name, created_at, updated_at) values('NICHOLSON',now(),now());
insert into brands ( name, created_at, updated_at) values('NITTO',now(),now());
insert into brands ( name, created_at, updated_at) values('NORDEN ',now(),now());
insert into brands ( name, created_at, updated_at) values('NYCSA',now(),now());
insert into brands ( name, created_at, updated_at) values('OBI',now(),now());
insert into brands ( name, created_at, updated_at) values('OMEGA',now(),now());
insert into brands ( name, created_at, updated_at) values('PERFECT',now(),now());
insert into brands ( name, created_at, updated_at) values('PERICO',now(),now());
insert into brands ( name, created_at, updated_at) values('PHILLIPS',now(),now());
insert into brands ( name, created_at, updated_at) values('PRETUL',now(),now());
insert into brands ( name, created_at, updated_at) values('PRODIN',now(),now());
insert into brands ( name, created_at, updated_at) values('PULKESA',now(),now());
insert into brands ( name, created_at, updated_at) values('RESISTOL',now(),now());
insert into brands ( name, created_at, updated_at) values('RIDGID',now(),now());
insert into brands ( name, created_at, updated_at) values('RIDMEX',now(),now());
insert into brands ( name, created_at, updated_at) values('RINO',now(),now());
insert into brands ( name, created_at, updated_at) values('ROCAMAR',now(),now());
insert into brands ( name, created_at, updated_at) values('ROTOPLAS ',now(),now());
insert into brands ( name, created_at, updated_at) values('RPM',now(),now());
insert into brands ( name, created_at, updated_at) values('RUGO',now(),now());
insert into brands ( name, created_at, updated_at) values('SALDAV',now(),now());
insert into brands ( name, created_at, updated_at) values('SCALA',now(),now());
insert into brands ( name, created_at, updated_at) values('SHOP-VAC',now(),now());
insert into brands ( name, created_at, updated_at) values('SIEMENS',now(),now());
insert into brands ( name, created_at, updated_at) values('SIKA',now(),now());
insert into brands ( name, created_at, updated_at) values('SILER ',now(),now());
insert into brands ( name, created_at, updated_at) values('SISTA',now(),now());
insert into brands ( name, created_at, updated_at) values('SKIL',now(),now());
insert into brands ( name, created_at, updated_at) values('SOPRANO',now(),now());
insert into brands ( name, created_at, updated_at) values('STABILIT',now(),now());
insert into brands ( name, created_at, updated_at) values('STANLEY ',now(),now());
insert into brands ( name, created_at, updated_at) values('STARK',now(),now());
insert into brands ( name, created_at, updated_at) values('STEREN',now(),now());
insert into brands ( name, created_at, updated_at) values('STREAMLINE',now(),now());
insert into brands ( name, created_at, updated_at) values('SURTEK',now(),now());
insert into brands ( name, created_at, updated_at) values('TAMER 2000',now(),now());
insert into brands ( name, created_at, updated_at) values('TANGIT',now(),now());
insert into brands ( name, created_at, updated_at) values('TECNOPLASTIC',now(),now());
insert into brands ( name, created_at, updated_at) values('THORSMAN',now(),now());
insert into brands ( name, created_at, updated_at) values('TIVOLY',now(),now());
insert into brands ( name, created_at, updated_at) values('TORILLO ',now(),now());
insert into brands ( name, created_at, updated_at) values('TOVER',now(),now());
insert into brands ( name, created_at, updated_at) values('TRUPER ',now(),now());
insert into brands ( name, created_at, updated_at) values('TUBOPLUS',now(),now());
insert into brands ( name, created_at, updated_at) values('TUK',now(),now());
insert into brands ( name, created_at, updated_at) values('TULMEX',now(),now());
insert into brands ( name, created_at, updated_at) values('TURNER ',now(),now());
insert into brands ( name, created_at, updated_at) values('UNION',now(),now());
insert into brands ( name, created_at, updated_at) values('URREA',now(),now());
insert into brands ( name, created_at, updated_at) values('VALEZZI',now(),now());
insert into brands ( name, created_at, updated_at) values('VALMEX ',now(),now());
insert into brands ( name, created_at, updated_at) values('VERDEPLUS',now(),now());
insert into brands ( name, created_at, updated_at) values('VICTORINOX',now(),now());
insert into brands ( name, created_at, updated_at) values('VIMALERT ',now(),now());
insert into brands ( name, created_at, updated_at) values('VISE-GRIP',now(),now());
insert into brands ( name, created_at, updated_at) values('VOLTECK',now(),now());
insert into brands ( name, created_at, updated_at) values('WD-40',now(),now());
insert into brands ( name, created_at, updated_at) values('WELD500',now(),now());
insert into brands ( name, created_at, updated_at) values('WELD-ON',now(),now());
insert into brands ( name, created_at, updated_at) values('WELLER',now(),now());
insert into brands ( name, created_at, updated_at) values('WERNER',now(),now());
insert into brands ( name, created_at, updated_at) values('WORCESTER',now(),now());

